---

- name: Install packages
  apt:
    name: '{{ item }}'
    force: true
  with_items:
    - acl
    - git
    - vim-gnome
    - build-essential
    - hh
    - qbittorrent
    - ubuntu-restricted-addons
    - ubuntu-restricted-extras
    - chromium-browser
