---

- name: Dotfiles alias
  shell: echo 'alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME"' >> $HOME/.bashrc
  # become: false
  # become_user: '{{ dotfiles_user }}'

- name: Bare git repo
  git:
    accept_hostkey: true
    repo: '{{ dotfiles_repo }}'
    bare: true
    dest: '{{ dotfiles_bare_path }}'
    # become: false
  # become_user: '{{ dotfiles_user }}'

- name: Normal git repo
  git:
    accept_hostkey: true
    repo: '{{ dotfiles_repo }}'
    dest: '{{ dotfiles_project_path }}'
    # become: false
  # become_user: '{{ dotfiles_user }}'
