---

- name: Bare git repo
  git:
    accept_hostkey: true
    repo: '{{ dotfiles_repo }}'
    bare: true
    dest: '{{ dotfiles_bare_path }}'
  become: true
  become_user: '{{ dotfiles_user }}'

- name: Normal git repo
  git:
    accept_hostkey: true
    repo: '{{ dotfiles_repo }}'
    dest: '{{ dotfiles_project_path }}'
  become: true
  become_user: '{{ dotfiles_user }}'
